"""your message

Revision ID: 314b5a7960c3
Revises: 43ceb3d698f4
Create Date: 2025-02-04 22:21:26.261709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314b5a7960c3'
down_revision = '43ceb3d698f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
